In [1]:
                                                    ###  “There are no facts, only interpretations.” ― Friedrich Nietzsche
#Numpy                                     
#-------
#-->Numpy is a Linear algebra for python.
#    It is also incrediblily fast as it has bindings to C libraries.

#-->Numpy comes with 1 Dimesionals vector or 2 dimensionals matrices but they can both be called as Array 1d or 2d.

In [1]:
import numpy as np

In [3]:
#Making a List

my_list1=[10,12,13,14]
my_list1

[10, 12, 13, 14]

In [4]:
#Making array from list

my_array1=np.array(my_list1)
my_array1

array([10, 12, 13, 14])

In [5]:
#List

my_list2=[22,23,24,25]
my_list2

[22, 23, 24, 25]

In [6]:
#Concatenating two list(list of list)

my_lists=[my_list1,my_list2]
my_lists

[[10, 12, 13, 14], [22, 23, 24, 25]]

In [7]:
#we can make multi dimensional array or matrix using this.

my_array2=np.array(my_lists)
my_array2

array([[10, 12, 13, 14],
       [22, 23, 24, 25]])

In [8]:
#Geting the shape of the Array

my_array2.shape

(2L, 4L)

In [9]:
#To find the data type of an Array

my_array2.dtype

dtype('int32')

In [10]:
#Creating zero array/Matrix

np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
#Special case array

array_only_zeros=np.zeros(6)

In [13]:
#datatype of zeros array

array_only_zeros.dtype

dtype('float64')

In [14]:
#creating 6*6 Mutidimensional arrays of only 1

np.ones([6,6])

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [15]:
#creating empty array

np.empty(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [16]:
#Identity Matrix or Array(Diagonal of one)

np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [17]:
#Creating an array,which conist of 0 to 4

np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
#Creating an array,which conist of elements from 2 and excluing 40 and an increment of 2

np.arange(2,30,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
#Using Array and Scalars

In [19]:
#Importing Python 3 Functionality in Python2

from __future__ import division

In [20]:
7/2

3.5

In [21]:
#Creating a Multi Dimensional Array

arr1=np.array([[1,2,3,4],[10,11,12,13]])
arr1

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [22]:
#Multi dimensional array Multiplication
#Each element multipyling to themselves

arr1*arr1

array([[  1,   4,   9,  16],
       [100, 121, 144, 169]])

In [23]:
# Array substraction

arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
#Arithmetic Operations

2/arr1

array([[ 2.        ,  1.        ,  0.66666667,  0.5       ],
       [ 0.2       ,  0.18181818,  0.16666667,  0.15384615]])

In [27]:
#To the power of 3

arr1**3

array([[   1,    8,   27,   64],
       [1000, 1331, 1728, 2197]])

In [28]:
#Indexing of Arrays
#--------------------

In [29]:
#Creating an array including 5 and excluding 15

arr1=np.arange(5,15)
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
#To get the value of 6th Index

arr1[6]

11

In [32]:
#To get value in certain Range based on Index

arr1[1:5]

array([6, 7, 8, 9])

In [33]:
#To set the value 100 to 0th to 5th index

arr1[0:5]=100

arr1

array([100, 100, 100, 100, 100,  10,  11,  12,  13,  14])

In [34]:
#Creating an array including 10 and excluding 25

arr1=np.arange(10,25)

arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
#Slice of an Array

slice_of_arr=arr1[0:7]

slice_of_arr

array([10, 11, 12, 13, 14, 15, 16])

In [36]:
#We can change the slice of an Array

slice_of_arr[:]=84

In [37]:
slice_of_arr

array([84, 84, 84, 84, 84, 84, 84])

In [38]:
#Original copy changed because to save memory

arr1

array([84, 84, 84, 84, 84, 84, 84, 17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
#To Copy the Array

arr1_copy=arr1.copy()

In [40]:
arr1_copy

array([84, 84, 84, 84, 84, 84, 84, 17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
#Indexing in 2D Array

arr_2d=np.array(([4,8,12],[16,20,24],[28,32,26]))

arr_2d

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 26]])

In [42]:
#Indexing always starts with 0,Here 1 means 2nd Row

arr_2d[1]

array([16, 20, 24])

In [43]:
#Here 0 means 1st Row

arr_2d[0]

array([ 4,  8, 12])

In [44]:
#Fetching a Particular Values
#Fetching first row and 2nd Column

arr_2d[0][1]

8

In [45]:
#2d Array Slicing
#arr_2d

arr_2d[:2,1:]

array([[ 8, 12],
       [20, 24]])

In [46]:
#Seeing Bottom Row

arr_2d[2]

array([28, 32, 26])

In [47]:
#Fancy Indexing

arr2d=np.zeros((4,4))

arr2d

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [48]:
#Length of an Array

arr_length=arr2d.shape[1]

arr_length

4L

In [49]:
#for every i set the value 1 

for i in range(arr_length):
    arr2d[i]=1
arr2d

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [50]:
#we change the value across the row

for i in range(arr_length):
    arr2d[i]=i
arr2d

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.]])

In [51]:
#passing same values to 2nd 3rd and 0th Row

arr2d[[2,3,0]]

arr2d

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.]])

In [52]:
#Array Transposition
##--------------------

In [53]:
#Creating an array of 10 row and 4 Coulumn

import numpy as np
arr=np.arange(40).reshape(10,4)

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [55]:
#Transpose
#The first row is transposed into first column simmilarly

arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38],
       [ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39]])

In [56]:
#Dot product

np.dot(arr.T,arr)

array([[4560, 4740, 4920, 5100],
       [4740, 4930, 5120, 5310],
       [4920, 5120, 5320, 5520],
       [5100, 5310, 5520, 5730]])

In [57]:
#Creating an 3 dimensional Matrix.

arr3d =np.arange(50).reshape(5,5,2)

arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [58]:
#Transposing a 3D Matrix

arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [59]:
#universal Array Function
#You can apply every value of an Array

In [60]:
import numpy as np
arr=np.arange(15)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
#square root of an array

np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739])

In [62]:
#calculating exponential value of an array

np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06])

In [63]:
#Random of Array
#Random Function
#Randn-Normal distributed random Number
#Creating random values array of size of 15 element

R=np.random.randn(20)
R

array([ 1.22585049,  1.89349005, -0.17539514, -1.95115498,  0.39526844,
        1.29662914,  0.67178426,  0.03228484, -0.13538245, -0.73179357,
        0.89560573,  0.60420255,  0.66393248,  0.6485112 ,  0.30011888,
        0.70793421,  0.04020269, -0.114267  ,  0.62566232,  1.87456728])

In [64]:
#Randn-Normal distributed random Number
#Creating random values array of size of 20 element

R1=np.random.randn(20)
R1

array([ 0.12520584,  0.55080723, -1.03330073,  1.6902986 , -0.76679586,
        0.83006832,  0.63861931, -0.46202736,  1.65331546,  1.0787801 ,
       -2.18431374,  2.24994605,  0.3247123 , -0.63504811, -0.02042539,
        0.12381185,  1.0247796 , -1.00451417, -0.87717608,  0.04731574])

In [65]:
#Binary Function

RF=np.add(R,R1)
RF

array([ 1.35105634,  2.44429728, -1.20869587, -0.26085638, -0.37152741,
        2.12669746,  1.31040357, -0.42974252,  1.51793301,  0.34698652,
       -1.28870802,  2.8541486 ,  0.98864479,  0.01346309,  0.27969349,
        0.83174606,  1.06498229, -1.11878117, -0.25151375,  1.92188302])

In [66]:
#Find Max
#Give maximum from both the Array

np.maximum(R,R1)

array([ 1.22585049,  1.89349005, -0.17539514,  1.6902986 ,  0.39526844,
        1.29662914,  0.67178426,  0.03228484,  1.65331546,  1.0787801 ,
        0.89560573,  2.24994605,  0.66393248,  0.6485112 ,  0.30011888,
        0.70793421,  1.0247796 , -0.114267  ,  0.62566232,  1.87456728])

In [67]:
#Find Min
#Give minimum from both the Array


np.minimum(R,R1)

array([ 0.12520584,  0.55080723, -1.03330073, -1.95115498, -0.76679586,
        0.83006832,  0.63861931, -0.46202736, -0.13538245, -0.73179357,
       -2.18431374,  0.60420255,  0.3247123 , -0.63504811, -0.02042539,
        0.12381185,  0.04020269, -1.00451417, -0.87717608,  0.04731574])

In [68]:
#To import the packages

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [69]:
#To know the version

import sys
import numpy as np
print sys.version
print np.__version__

2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]
1.11.3


In [70]:
#Numpy Array Basics
##-----------------

In [71]:
#Creating an array
np1=np.arange(20)

np1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
#Few Functions on array
#Only last output will be displayd ;)

np1.min()
np1.max()
np1.mean()
np1.std()

5.7662812973353983

In [75]:
#Three methods to get the same output and boolean selection seems more efficient.

##Method--1

#Known as List Comprehension.

#Getting all the values divisible by 2  in our Array
##Using list comprehension and iterate value of an array we can test whether or not the value are divisible by 2

list=[10,15,16,18,20]
arr=np.array(list)
arr

y=[x for x in arr if x%2==0]

for z in y:
    print(z)


10
16
18
20


In [79]:
##Method--2

#Getting all the values divisible by 2  in our Array.
## We can use filter to get the same result.lambda--that will apply to each item within the array.

list=[10,15,16,18,20]
arr=np.array(list)


x1=filter(lambda x:x%2==0,arr)

for y1 in x1:
    print(y1)

10
16
18
20


In [85]:
##Method--3
#Known as Boolean Selection

#Getting all the values divisible by 2  in our Array.

list=[10,15,16,18,20]
arr=np.array(list)

arr%2==0
a1=arr[arr%2 ==0]

for b1 in a1:
    print(b1)

10
16
18
20


In [94]:
#True is equivalent to 1 or anything greater than 1 is True
##passing boolean as dtype(it will give output in this format)

x=np.array([True,2,3,4,0],dtype="bool")
x

array([ True,  True,  True,  True, False], dtype=bool)

In [95]:
#True is equivalent to 1 or anything greater than 1 is True
##passing float as dtype(it will give output in this format)

y=np.array([True,4,3,0,2],dtype="float")
y

array([ 1.,  4.,  3.,  0.,  2.])

In [104]:
#To Get the Size of an Array

list=[10,11,12,34,56,78,98,76,55,47,78]
x=np.array(list)
print(x.size)
print(x.shape)

11
(11L,)


In [5]:
#To get the Minimum and Maximuv Value Index
#using print to display more then one output in Jupyter
#As index starts from 0 in Python

import numpy as np
list=[45,87,49,32]
x=np.array(list)
print(x.argmin())
print(x.argmax())

3
1


In [12]:
#Linspace-->(from,to,how many) find equal interval value wiythin the Range
#output will be in Float

np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [14]:
#To make the Output in int

np.linspace(0,10,11).astype('int')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])